### ISSUE TITLE
z-index values are getting flattened to 1 or 2. Does anyone know which of css-loader, style-loader, sass-loader, and postcss-loader could be responsible for this? 

### ISSUE THREAD

**Issue by adrianocr** [hayes0724/shopify-packer#129]
Converted this project from Slate. Everything working fine but my z-index values that are usually like 5000 or 9999999 are getting flattened out to the values 1 or 2. 

The styles are all .scss files so I'm assuming its one of either style-loader or sass-loader but I can't find any info in the webpack docs about options or configs that may be resulting in this. 

Has anyone dealt with a similar situation?

**Comment by GuillermoCasanova** [comment]
Just ran into this issue as well. Z-index values set to 4 are also flattened to 1.

**Comment by iPhenan** [comment]
Add `zindex: false` to Your `postcss.config.js` it should fix your issue
```
module.exports = {
  plugins: [
    require("postcss-preset-env"),
    require("cssnano")({
      preset: [
        "advanced",
        {
          zindex: false,
        },
      ],
    }),
  ],
};
```
