### ISSUE TITLE
TypeError: Cannot read property 'store' of undefined

### ISSUE THREAD

**Issue by steven-orfu** [hayes0724/shopify-packer#13]
When running build. I get the following.
`
\@hayes0724\shopify-packer\src\env\index.js:25
    process.env[key] = env[name][_getConfigKey(key)];
                                ^

TypeError: Cannot read property 'store' of undefined
`

Feels like Im missing something obvious

**Comment by JackCA** [comment]
I think there's a mistake in the docs or the code but you can work around this by excluding the `themes` key in `packer.env.json` like this:
```json
{
    "development": {
      "id": "74500041118",
      "password": "ebd6ce7f27aae8cdafb8111a5b887b9",
      "store": "my-store-name.myshopify.com",
      "ignore": [
        "settings_data.json"
      ]
    }
}
```

**Comment by Eben-Hafkamp** [comment]
Thanks @JackCA 

After installing packer and running the init command I had a config.json in the root of my new project even though the cli was looking for a packer.env.json file and the structure of the config.json was also wrong as you pointed out.

Is this bug only happening to me?

**Comment by hayes0724** [comment]
Just updated the docs to reflect recent changes the `config.json` was replaced `packer.env.json` and "theme" key is no longer part of the file. The goal was to move settings and theme env data to separate files (packer.env.json and packer.config.js)

Documentation was updated in v1.3.1
