### ISSUE TITLE
Using Environment Variables for environment config

### ISSUE THREAD

**Issue by JackCA** [hayes0724/shopify-packer#14]
Is there a method for using environment variables for the values that are used in `packer.env.json`? I need to avoid checking in that file because it has sensitive credentials and it would be nice to use environment variables for assigning those values.

[Themekit, for example, allows string interpolation for this.](https://shopify.github.io/themekit/configuration/)

Thanks for creating this thoughtful library, looking forward to trying it out.

**Comment by mrpacman101** [comment]
i just git ignored the default packer.env.json and config.json and created a sample.packer.env.json for the devs. This way they can just use the sample file and create their own locally. No need to mess around with local env variables.

**Comment by hayes0724** [comment]
All packer values can be loaded from env values, the config file is not needed if your using env (example CI deploys). This needs to be documented better. Although not required, `packer.config.json` is ignored by default in packer theme.

@mrpacman101 This is the preferred method that I use. It's best to let each developer keep a local copy and have a sample file for them to populate.

The env values are located in `src/env/packer-env.schema.js` for reference (this should be added to the docs for CI use)

```javascript
const commonPaths = require('../config/common-paths');

module.exports = {
  ...commonPaths,

  // The environment variable key which contains the name of the environment
  // Packer is running in
  'env.keys.name': 'PACKER_ENV',

  // The environment variable key which contains the myshopify.com URL to your
  // Shopify store
  'env.keys.store': 'PACKER_STORE',

  // The environment variable key which contains the API password generated from
  // a Private App
  'env.keys.password': 'PACKER_PASSWORD',

  // The environment variable key which contains the ID of the theme you wish to
  // upload files to
  'env.keys.id': 'PACKER_ID',

  // The environment variable key which contains a list of file patterns to
  // ignore, with each list item separated by ':'
  'env.keys.ignore': 'PACKER_IGNORE',

  // The environment variable key which contains a list of file patterns to
  // allow deployment to live themes
  'env.keys.live': 'PACKER_LIVE',
};

```

**Comment by JackCA** [comment]
@hayes0724 thank you, that helps a ton.
