### ISSUE TITLE
[BUG] Chalk v5 does not allow 'require' breaking new installations

### ISSUE THREAD

**Issue by henrybarn** [hayes0724/shopify-packer#147]
**Describe the bug**
I just setup packer for the first time and could not run any commands due to chalk being imported with require since it is now an ESM. Chalk is pinned at latest in the package.json. Changing this to ^4 fixed the issue for me.

**To Reproduce**
1. npm install on a clean environment.
2. Run packer init

**System (please complete the following information):**
 - OSX
 - Node 12.19
 - Npm 6.14.8

**Packer (please complete the following information):**
 - Latest version

**Theme (please complete the following information):**
 - [Shopify Packer theme](https://github.com/hayes0724/packer-blank-theme)
 - Latest version

**Comment by quentin-f451** [comment]
Same problem here, maybe Chalk would need to be downgraded for the moment?

**Comment by Eben-Hafkamp** [comment]
All modules in package.json that reference the "latest" version need to reference a version of themselves that support commonjs requires() instead. Unless using the latest version of this library which was migrated to webpack5 and resolved the package names

**Comment by marioloncarek** [comment]
we fixed the problem by manually setting chalk to 4.1.2 and running npm install in packers global installation folder

**Comment by Kadreev** [comment]
I can confirm by setting chalk to 4.1.2 and reinstalled the module, the issue is resolved. 

Some more details for newbies: in the global installation folder ...\node_modules\@hayes0724\shopify-packer\
file package.json
"chalk": "latest" >>>> "chalk": "^4.1.2"
then just run from the same dir
npm uninstall chalk
npm install chalk@4.1.2 --save
