### ISSUE TITLE
Missing dependencies on blank template

### ISSUE THREAD

**Issue by JackCA** [hayes0724/shopify-packer#15]
I had to install the following dev dependencies after a fresh init:

- sass-loader
- style-loader
- concat-style-loader
- css-loader
- sass

**Comment by hayes0724** [comment]
Please add steps to reproduce, packer version, blank theme version and if you are customizing the `dev.config.js` or `prod.config.js` files.

Packer (using global install) has all of the above items and any themes will use the global version unless you modify the above files. If you do modify them you will need to install in the theme. For example if you wish to use a different version of `sass-loader` you would install inside theme and

**Comment by JackCA** [comment]
Sorry for the misdirect here -- I avoid adding things globally so that may have been the cause. Although, every other example of a lib that I've done this on it's worked, but that's on me since you have it in your instructions.
