### ISSUE TITLE
"Error downloading files" when running `packer theme:download`

### ISSUE THREAD

**Issue by nitaic** [hayes0724/shopify-packer#16]
When running `packer theme:download` I get the following error:

`
Error downloading files

TypeError: obj[key].reduce is not a function
`

Am I missing something?

Also, I'm curious what workflow you use for making sure you have the latest them files. I'm assuming you need to run theme:download to make sure you always have the latest files in case changes were made via the shopify editor?

_Thanks for making this great tool available._

**Comment by SirCameron** [comment]
same issue here.

**Comment by mrpacman101** [comment]
When a client installs an app on the live store, i usually create a new branch and pull the changes from the live theme - thumbs up for finding a way around this issue @SirCameron ! 
Once i have the changes i run my default workflow -  deploy the code to my development theme copy - test it - create a pull request and then it will be eventually deployed again to the live theme. I found this to be a hard process if we have lots of clients who install apps and remove them again. Another way would be to only manually install app files but thats a painful process...

**Comment by hayes0724** [comment]
Typo in the ignore files flag was causing this and has been fixed in v1.3.2 and pr #32
