### ISSUE TITLE
Error on deploy. Start and watch have no effect.

### ISSUE THREAD

**Issue by SirCameron** [hayes0724/shopify-packer#18]
Running ```packer deploy``` spits out:
```
↑  Uploading to Shopify...

- Error: ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/@shopify/themekit/bin/theme'

Files overwritten successfully!
```

running ```packer start``` or ```packer watch``` does not actually change any files on shopify.

**Comment by hayes0724** [comment]
Packer relies on shopify themekit for deployments (start and watch) make sure you have it installed globally. This should be added to the documentation.

https://shopify.github.io/themekit/
