### ISSUE TITLE
freezes at "Compiling..."

### ISSUE THREAD

**Issue by adardesign** [hayes0724/shopify-packer#2]
⠴ Compiling...

**Comment by Eben-Hafkamp** [comment]
@adardesign Long time, but do you remember what the solution was?

**Comment by LuckyGStar** [comment]
@Eben-Hafkamp , @adardesign , if it is keep saying `compiling....` , please update any liquid file and click `ctrl + save`. Then it will start compiling.

**Comment by Eben-Hafkamp** [comment]
@LuckyGStar That's pretty odd, I'll dig into the module to see if there are any other work arounds. My browser always refreshes before the build tool has finished compiling leading me to manual refreshing after liquid updates.

**Comment by LuckyGStar** [comment]
@Eben-Hafkamp , yeah. I also experienced it when I have been worked with shopify packer. I haven't had a chance to dig into the module of packer yet but seems like it is refreshing browser before the callback of update.

**Comment by Eben-Hafkamp** [comment]
@LuckyGStar My thought exactly, I'll update with a solution if I get a chance to look into it.
