### ISSUE TITLE
Removed src file is still in /dist after build

### ISSUE THREAD

**Issue by yi-bbc** [hayes0724/shopify-packer#22]
All the snippets and templates files I just removed from /src folder still exist in the /dist folder after a successful build.

Is this intentional?

**Comment by GuillermoCasanova** [comment]
I ran into this issue as well earlier last week, had to delete /dist entirely manually when this happened so it built as expected. Not sure if this is intentional. Doesn't seem like it.

**Comment by hayes0724** [comment]
Clean webpack plugin was removing generated files from dist/assets instead of all files in dist folder, fixed with v1.3.0 and PR  #28
