### ISSUE TITLE
Dynamic sections - do not render

### ISSUE THREAD

**Issue by soheimam** [hayes0724/shopify-packer#23]
Dynamic sections are not being output in the {{ content_for_index }} section of the Shopify template. Sections will only render using the {% include %} method

**Comment by hayes0724** [comment]
Please include which version of packer you are using `packer -v` and what version of [Packer Theme](https://github.com/hayes0724/packer-blank-theme) if you are using that. 

I would suggest using the latest version of both, I use this daily and I'm not able to reproduce this issue.
