### ISSUE TITLE
[BUG] Extra single quote being loaded in the style-tags.liquid file 

### ISSUE THREAD

**Issue by GuillermoCasanova** [hayes0724/shopify-packer#24]
**Describe the bug**
When running packer build, the built theme contains a single " ` " right at the beginning of <body>. This makes the page move downward. I have to manually remove this quote from the code in Shopify. I found this single quote is inside of style-tags.liquid inside of /dist

**To Reproduce**
1. packer build 
2. packer deploy (optional to view in production)
3. Go to /dist folder and check style-tags.liquid

**Expected behavior**
This single quote shouldn't be here. I believe the quote is a straggler quote inside of style-tags.html of the shopify-packer source code. Screenshots below. 

**Screenshots**
Compiled style-tags.liquid: 
https://ibb.co/rthLMWy

Shopify Packer Webpack style-tags.html
https://ibb.co/PcN2XvQ

Quote above web page: 
https://ibb.co/M5VmdHJ

**System (please complete the following information):**
 - OS: Mac 
 - Node Version 10.13.0
 - NPM Version 6.4.1
 - Browser (All) 

**Packer (please complete the following information):**
 - Version [e.g. 1.2.1]

**Theme (please complete the following information):**
 - [Shopify Packer theme](https://github.com/hayes0724/packer-blank-theme) [e.g. True]

**Comment by hayes0724** [comment]
Fixed typo in style-tags.html with v1.3.0 and PR #28
