### ISSUE TITLE
[BUG] Crashes on liquid issue

### ISSUE THREAD

**Issue by adrianocr** [hayes0724/shopify-packer#49]
**Describe the bug**
If you create a section and get something wrong in the liquid code, such as forgetting to close an "include" snippet, or leave an extra comma in a schema definition, shopify replies with an error. That error causes packer to panic and exit instead of simply displaying the issue and waiting to re-upload the file after you fix it.

**To Reproduce**
Follow standard set up and set up instructions in the github docs. Make an error in the liquid code on purpose. Wait for themekit to upload the file and reply with the error.

**Expected behavior**
Should just display the error and continue running in case you decide to fix it. Right now it requires you run `packer watch` or `packer start` all over again.

**System (please complete the following information):**
 - OS: macOS big sur
 - Node Version: v14.15.3
 - NPM Version: npm@6.14.9
 - Browser: every

**Packer (please complete the following information):**
 - Version: v1.3.4
 - 
**Theme (please complete the following information):**
 - [Shopify Packer theme](https://github.com/hayes0724/packer-blank-theme) [true]
 - Version: latest

**Comment by hayes0724** [comment]
I had changed an error to exception on a recent update that causes this. The goal was for it to exit when config file has issues but it throws on themekit errors now, should be a quick fix.

**Comment by hayes0724** [comment]
Fixed in v1.3.6
