### ISSUE TITLE
Customer templates not being uploaded

### ISSUE THREAD

**Issue by Eben-Hafkamp** [hayes0724/shopify-packer#54]
My packer was throwing customer templates into the /templates folder instead of /templates/customers

Fixed with the following: 

`{
  from: config.get('theme.src.templates'),
          to: config.get('theme.dist.templates'),
          globOptions: {
            ignore: ['**/customers/**'],
          },
        },
        {
          from: config.get('theme.src.customers'),
          to: config.get('theme.dist.customers'),
        },`

**Comment by Eben-Hafkamp** [comment]
is it possible to delete an issue after creating it in github.. lol?

**Comment by hayes0724** [comment]
Yes, it's been weird recently with updates to both discussions and issues. I had to wait several weeks to transfer an issues to discussion.
