### ISSUE TITLE
[BUG] Module not found: Error: Can't resolve 'concat-style-loader'

### ISSUE THREAD

**Issue by GarrettWeinberg** [hayes0724/shopify-packer#59]
**Describe the bug**
I set up a fresh install and when i run `packer start` i receive the error `Module not found: Error: Can't resolve 'concat-style-loader`

once i install concat-style-loader i get this error

`./src/scripts/layout/theme.js
Module not found: Error: Can't resolve 'concat-style-loader' in '/Users/rebelmac010921/sites/anther-2021'
 @ ./src/scripts/layout/theme.js 14:0-40
 @ multi /Users/rebelmac010921/.config/yarn/global/node_modules/@hayes0724/shopify-packer/src/webpack/hot-client.js ./src/scripts/layout/theme.js

./src/scripts/layout/theme.js
Module not found: Error: Can't resolve 'style-loader' in '/Users/rebelmac010921/sites/anther-2021'
 @ ./src/scripts/layout/theme.js 13:0-33
 @ multi /Users/rebelmac010921/.config/yarn/global/node_modules/@hayes0724/shopify-packer/src/webpack/hot-cli`

once i install concat-style-loader and style-loader i receive this error

`./src/scripts/layout/theme.js
Module not found: Error: Can't resolve 'css-loader' in '/Users/rebelmac010921/sites/anther-2021'
 @ ./src/scripts/layout/theme.js 13:0-33
 @ multi /Users/rebelmac010921/.config/yarn/global/node_modules/@hayes0724/shopify-packer/src/webpack/hot-client.js ./src/scripts/layout/theme.js`

once i install css-loader i receive this error

`./src/scripts/layout/theme.js
Module not found: Error: Can't resolve 'sass-loader' in '/Users/rebelmac010921/sites/anther-2021'
 @ ./src/scripts/layout/theme.js 13:0-33
 @ multi /Users/rebelmac010921/.config/yarn/global/node_modules/@hayes0724/shopify-packer/src/webpack/hot-client.js ./src/scripts/layout/theme.js`

once i install sass-loader i receive this error 

`./src/styles/theme.scss (./node_modules/css-loader/dist/cjs.js??ref--7-1!/Users/rebelmac010921/.config/yarn/global/node_modules/@hayes0724/shopify-packer/node_modules/postcss-loader/dist/cjs.js??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./src/styles/theme.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/Users/rebelmac010921/sites/anther-2021/node_modules/sass-loader/dist/index.js:25:24)
 @ ./src/styles/theme.scss 2:12-275 9:17-24 13:7-14 45:20-27 47:4-60:5 49:6-59:7 50:38-45 56:26-33 58:21-28 68:15-22
 @ ./src/scripts/layout/theme.js
 @ multi /Users/rebelmac010921/.config/yarn/global/node_modules/@hayes0724/shopify-packer/src/webpack/hot-client.js ./src/scripts/layout/theme.js`

NOTE: If i run `packer watch` local host does work and theme files (.liquid) work and display, but no styles come through.

**To Reproduce**
Steps to reproduce the behavior: (followed quick start guide)
1. packer init <dir>
2. cd into <dir>
3. Add app password and store url to config.json
4. packer theme:create --name=my-theme-name
5. yarn (also tried npm install)
5. packer start

**Expected behavior**
styles to be compiled without errors

**Screenshots**

**System (please complete the following information):**
 - OS: OSX Big Sur
 - Node Version: v14.16.0 (tried 10 and 12 also)
 - NPM Version: 6.14.11
 - Browser: chrome

**Packer (please complete the following information):**
 - Version: Shopify Packer - v1.3.4

**Theme (please complete the following information):**
"name": "packer-blank-theme",
  "version": "1.0.9",

**Comment by musdy** [comment]
+

**Comment by musdy** [comment]
Hey @GarrettWeinberg ,

This helped me fix it:
https://exerror.com/typeerror-this-getoptions-is-not-a-function-in-vue-js/

**Comment by hayes0724** [comment]
@GarrettWeinberg `concat-style-loader` is no longer used in v2.0.0
