### ISSUE TITLE
More information on how to use with pre-built html templates

### ISSUE THREAD

**Issue by holymp2006** [hayes0724/shopify-packer#6]
My colleague already made html templates for our new store. 
These templates have sub-directories in their 'assets' directory. example "assets/css/...",  "assets/js/...", "assets/plugins/font-awesome/...",  "assets/images/...";

In the process of splitting and converting these templates into '.liquid' files; and deploying, I found out that the Shopify "assets" directory does not support sub-directories. (I'm very new to Shopify theme'ing)

I came here searching for a way to flatten the original 'assets' directory, so that all references to the assets in the in all 'js' and 'css' files, will be 'corrected', before I "theme deploy".

Is this something I can achieve with this package? If yes, a little help please on how to use the package to go about it.

**Comment by hayes0724** [comment]
@holymp2006 You are correct, Shopify will expect to find all (s)css, js and images in side of the flat assets folder.

When you run `packer deploy` it send all files in the `dist` folder to the Shopify theme listed in your config (you can also run `packer zip` for a zipped file you can upload)

Before running `packer deploy` you should always run `packer build` which will create a production ready build of your files in `src` folder. 

Packer uses webpack for compiling and preparing files for Shopify. Part of the webpack set is copying all files from `src/assets` to `dist/assets` flattened. 

src/webpack/parts/core.js

```
       {
          from: config.get('theme.src.assets'),
          to: config.get('theme.dist.assets'),
          flatten: true,
        },
```
By running `packer build` you should have a flattened assets folder in dist. Which you can reference in an any template using liquid

Ideally you would want to load the scripts and css using a webpack entrypoint and not from assets, for example importing them into `theme.js`.
