### ISSUE TITLE
[BUG] --nodelete does not seem to work

### ISSUE THREAD

**Issue by fcisio** [hayes0724/shopify-packer#60]
**Describe the bug**
When doing `packer deploy --nodelete`, everything gets replaced by the build.
So ignored files are deleted, this includes the settings_data.json

**Comment by hayes0724** [comment]
Packer was not passing the no delete flag to themekit. I also created basic theme info output so you know what the settings are when you deploy

```
↑  Uploading to Shopify...
i Deploy Mode: noDelete
i Environment: live 
```

**Comment by Monolith-agency** [comment]
@hayes0724 
Sounds awesome! Thanks
