### ISSUE TITLE
[BUG] create a new project is not working

### ISSUE THREAD

**Issue by nvilus** [hayes0724/shopify-packer#67]
When I try to create a new project with `packer init <dirname>` terminal just show "Extracting the files from archive..." without stopping

**To Reproduce**
1. packer init dirname
2. showing "Extracting the files from archive..." 

**System:**
 - OS: macOS Catalina
 - Node Version 15.12.0
 - NPM Version 7.6.3
 - Browser chrome

**Packer:**
 - Version v2.0.1

**Comment by hayes0724** [comment]
Confirmed the bug, I'm stuck here too

```
PS H:\shopify\tools> packer init test
⠙ Extracting the files from archive...
```
After canceling, I checked and the files are extracted but have not been moved to root dir, renamed, or the zip file removed.

I think it's an issue with extract zip v2+ of packer uses extract-zip v2.0.1 vs v1.7.0
