### ISSUE TITLE
[BUG] Packer start report missing style-loader

### ISSUE THREAD

**Issue by OneX** [hayes0724/shopify-packer#70]
**Describe the bug**
After cloning repo from coworker, i run yarn install.

When running 'packer start', i got error in my terminal:
 
ERROR in ./src/scripts/layout/theme.js 13:0-33
Module not found: Error: Can't resolve 'style-loader' in '/Users/josipanic/Projekti/the-hardscape-exchange'
resolve 'style-loader' in '/Users/josipanic/Projekti/the-hardscape-exchange'
  Parsed request is a module
  using description file: /Users/josipanic/Projekti/the-hardscape-exchange/package.json (relative path: .)
    resolve as module
      looking for modules in /Users/josipanic/.config/yarn/global/node_modules/@hayes0724/shopify-packer/node_modules
        single file module
          using description file: /Users/josipanic/.config/yarn/global/node_modules/@hayes0724/shopify-packer/package.json (relative path: ./node_modules/style-loader)
            no extension
              /Users/josipanic/.config/yarn/global/node_modules/@hayes0724/shopify-packer/node_modules/style-loader doesn't exist
            .js
              /Users/josipanic/.config/yarn/global/node_modules/@hayes0724/shopify-packer/node_modules/style-loader.js doesn't exist
        /Users/josipanic/.config/yarn/global/node_modules/@hayes0724/shopify-packer/node_modules/style-loader doesn't exist
      looking for modules in /Users/josipanic/.config/yarn/global/node_modules/@hayes0724/shopify-packer/src
        single file module
          using description file: /Users/josipanic/.config/yarn/global/node_modules/@hayes0724/shopify-packer/package.json (relative path: ./src/style-loader)
            no extension
              /Users/josipanic/.config/yarn/global/node_modules/@hayes0724/shopify-packer/src/style-loader doesn't exist
            .js
              /Users/josipanic/.config/yarn/global/node_modules/@hayes0724/shopify-packer/src/style-loader.js doesn't exist
        /Users/josipanic/.config/yarn/global/node_modules/@hayes0724/shopify-packer/src/style-loader doesn't exist
      looking for modules in /Users/josipanic/Projekti/the-hardscape-exchange/node_modules
        single file module
          using description file: /Users/josipanic/Projekti/the-hardscape-exchange/package.json (relative path: ./node_modules/style-loader)
            no extension
              /Users/josipanic/Projekti/the-hardscape-exchange/node_modules/style-loader doesn't exist
            .js
              /Users/josipanic/Projekti/the-hardscape-exchange/node_modules/style-loader.js doesn't exist
        /Users/josipanic/Projekti/the-hardscape-exchange/node_modules/style-loader doesn't exist
      looking for modules in /Users/josipanic/Projekti/the-hardscape-exchange
        single file module
          using description file: /Users/josipanic/Projekti/the-hardscape-exchange/package.json (relative path: ./style-loader)
            no extension
              /Users/josipanic/Projekti/the-hardscape-exchange/style-loader doesn't exist
            .js
              /Users/josipanic/Projekti/the-hardscape-exchange/style-loader.js doesn't exist
        /Users/josipanic/Projekti/the-hardscape-exchange/style-loader doesn't exist

Also, seems there are missing node modules in my global and project folder.

**Expected behavior**
Packer local development will start

**System (please complete the following information):**
 - OS: [OSX]
 - Node Version [15.20.0]
 - NPM Version [7.6.3]
 - Browser [All]

**Packer (please complete the following information):**
 - Version [2.0.13]

**Theme (please complete the following information):**
 - [Shopify Packer theme](https://github.com/hayes0724/packer-blank-theme) [True]
 - Version [1.0.13]

**Comment by OneX** [comment]
@hayes0724 how does the installation run? if i run yarn install in my project folder it installs all module within package json of folder, but it ignores one from shopify-packer folder in yarn global directory.

This are the modules that are added to /Users/josipanic/.config/yarn/global/node_modules/@hayes0724/shopify-packer/node_modules/

<img width="677" alt="Slika zaslona 2021-03-31 u 17 06 21" src="https://user-images.githubusercontent.com/3229119/113166817-6c28a800-9243-11eb-8be3-9a5b5fa37e76.png">

**Comment by hayes0724** [comment]
1. Packer only needs to be installed once globally and is independent of any theme setup, unless you have build tools like style loader inside your theme, even then in most cases it will still work normally. I would need to see your package.json for the theme to confirm but I doubt that's the issue.

2. Your packer global install looks like it's missing a ton of packages, I just checked my current install and the same folder has 1026 folders vs 13 I see above.

I think the issue is the install and I would try removing and reinstalling. Packer can be run anywhere so you should be able to get output from:
```
packer -v
packer help
```

I'm guessing that won't work currently. You should also see at a minimum folders for the following packages:

```
 "@babel/core": "^7.13.10",
    "@shopify/themekit": "^1.1.7",
    "archiver": "^5.3.0",
    "array-flatten": "^3.0.0",
    "axios": "^0.21.1",
    "babel-loader": "^8.2.2",
    "browser-sync": "^2.26.14",
    "chalk": "latest",
    "console-control-strings": "^1.1.0",
    "copy-webpack-plugin": "8.0.0",
    "cors": "^2.8.5",
    "crypto": "^1.0.1",
    "css-loader": "5.1.3",
    "download": "^8.0.0",
    "eslint": "^7.22.0",
    "express": "^4.17.1",
    "extract-zip": "^2.0.1",
    "fibers": "^5.0.0",
    "figlet": "^1.4.0",
    "figures": "^3.2.0",
    "file-loader": "^6.2.0",
    "fs-extra": "^9.1.0",
    "html-webpack-plugin": "^5.3.1",
    "html-webpack-tags-plugin": "^3.0.0",
    "inquirer": "^8.0.0",
    "ip": "^1.1.5",
    "mini-css-extract-plugin": "^1.3.9",
    "minimatch": "^3.0.4",
    "minimist": "^1.2.5",
    "ora": "^5.4.0",
    "portscanner": "^2.2.0",
    "postcss": "^7.0.35",
    "postcss-loader": "^5.2.0",
    "prettier": "^2.1.2",
    "sass": "^1.32.8",
    "sass-loader": "^11.0.1",
    "selfsigned": "^1.10.8",
    "style-loader": "^2.0.0",
    "stylelint": "^13.12.0",
    "stylelint-webpack-plugin": "^2.1.1",
    "table": "^6.0.7",
    "tapable": "^2.0.0",
    "url-loader": "^4.1.1",
    "webpack": "^5.27.1",
    "webpack-bundle-analyzer": "^4.4.0",
    "webpack-cli": "^4.5.0",
    "webpack-dev-middleware": "^4.1.0",
    "webpack-dev-server": "^3.11.2",
    "webpack-hot-middleware": "^2.25.0",
    "webpack-merge": "^5.7.3",
    "yargs": "^16.2.0"
```

**Comment by OneX** [comment]
@hayes0724 seems like it works using npm i @hayes0724/shopify-packer -g, but not with yarn command. If you use yarn it complains about missing node modules, also yarn installs all dependencies in global node module folder, but seems like they are not linked correctly.
