### ISSUE TITLE
[BUG] Multiple assets emit different content to the same filename

### ISSUE THREAD

**Issue by marcelaerts** [hayes0724/shopify-packer#71]
**Describe the bug**
I followed the steps in the documentation up to Existing project. After running "packer start" I get the following errors:
ERROR in Conflict: Multiple assets emit different content to the same filename ../snippets/script-tags.liquid
ERROR in Conflict: Multiple assets emit different content to the same filename ../snippets/style-tags.liquid

**To Reproduce**
1. packer init <dirname>
2. yarn install
3. packer start

**Expected behavior**
These errors prevent changes in my theme. This needs to be resolved to make it work. 

**System (please complete the following information):**
 - OS: macOS Bug Sur 11.2.3
 - Node Version: 12.21.0
 - Yarn Version: 1.22.10
 - Browser: Chrome

**Packer (please complete the following information):**
 - Version: v2.1.1

**Comment by hayes0724** [comment]
This can happen when there are files shared between both layout and theme entry points in webpack 5. You can disabled shared bundles, let me know if this works for you.

packer-config.js

```
// Override default packer settings and config using this file
module.exports = {
  'build.sharedBundles': false,
}

```

**Comment by hayes0724** [comment]
This is common for any Shopify build system. You need SSL to proxy the liquid files and this requires a *trusted* cert. The only cert you can use locally will be a "self signed cert" which all browsers will not trust initially, unless you create or have a CA (cert authority) to issue it. When your browser sees the self signed cert it will block the network request (all js files) and the site will render without css or js.

All you need to do is accept/trust the cert on 127.0.0.1:3001 note you may have done this already for 127.0.0.1:3000 where everything but the js/css is served from.

**Quick fix** 
1. look in the developer console on chrome (make sure it is open before loading the page), look for the red error message with theme files should be several, example: `https://127.0.0.1/layout.theme.js`.
2. Right click, then click open in new tab, warning should appear, click proceed, then refresh the website

see docs on ssl for more details: [SSL Docs](https://hayes0724.github.io/shopify-packer/docs/ssl)

**Comment by marcelaerts** [comment]
The errors are still there:
ERROR in Conflict: Multiple assets emit different content to the same filename ../snippets/script-tags.liquid
ERROR in Conflict: Multiple assets emit different content to the same filename ../snippets/style-tags.liquid

// Override default packer settings and config using this file
module.exports = {
  'build.sharedBundles': false,
}

This is not working.

**Comment by hayes0724** [comment]
@marcelaerts can you check your src/assets folder for the above files?

They should be generated automatically by webpack html plugin. If you have them in the above folder (can happen if you download from live site) it will cause it be generated twice and webpack won't know which to use.
