### ISSUE TITLE
[BUG] New webpack 5 version has several issues with postcss plugins

### ISSUE THREAD

**Issue by adrianocr** [hayes0724/shopify-packer#72]
**Describe the bug**
The new 2.x versions of packer causes several postcss plugins like tailwindcss, postcss-import, and postcss-nested to issue an error, "PostCSS plugin [XXX] requires PostCSS 8""

**To Reproduce**
1. install (or upgrade) packer 2.x globally (this happens with both yarn and npm)
2. add the following to your postcss.config.js file: 
```
module.exports = {
  plugins: [
    require('postcss-import'),
    require('tailwindcss'),
    require('postcss-preset-env')({
      stage: 1, 
      features: {
        'focus-within-pseudo-class': false
      } 
    }),
    require('postcss-nested'),
    require('autoprefixer'),
    // require('postcss-preset-env'),
    require('cssnano')({
      preset: 'advanced',
    })
  ]
}
```
3. import css file in your js template entrypoint
3. `packer start`

**System (please complete the following information):**
 - OS: macOS 11.2.3
 - Node Version v15.11.0 (also happens with v14.16.0)

**Packer (please complete the following information):**
 - Version 2.x (any of them, I specifically tried several)

**Theme (please complete the following information):**
 - [Shopify Packer theme](https://github.com/hayes0724/packer-blank-theme) [True]

**Comment by hayes0724** [comment]
This is expected and have run into this recently. Tailwind 2 (recently released) uses PostCSS 8, previously it used PostCSS 7. Many other tools like cssnano have not released updates for PostCSS 8, they will in v5 which is close to release.

To use tailwind v2 you need to:
1. add postcss 8
2. replace cssnano with autoprefixer (or add cssnano@next for unreleased v5)

For a working example see this repo:
[Packer Theme - Tailwind 2](https://github.com/hayes0724/packer-blank-tailwind2)
