### ISSUE TITLE
[FEAT] --allow-live flag

### ISSUE THREAD

**Issue by fcisio** [hayes0724/shopify-packer#75]
**Is your feature request related to a problem? Please describe.**
When working on a development Shopify account, I work on the published theme.

But I would need to be able to pass the `--allow-live` flag in order to do that.

**Additional context**
It doesn't seem to work currently

**Comment by hayes0724** [comment]
The flag is a work in progress, you can update your env with a live setting that will do the same thing.

[docs](https://hayes0724.github.io/shopify-packer/docs/config/environment)

```
   "development": {
      "id": "74500041118",
      "password": "ebd6ce7f27aae8cdafb8111a5b887b9",
      "store": "my-store-name.myshopify.com",
      "live": "false",
      "ignore": [
        "settings_data.json"
      ]
    }
```

Set live to true

**Comment by hayes0724** [comment]
--allowLive flag has been added in v2.1.7
