### ISSUE TITLE
[BUG] Build Fails when importing same module in both scripts/layout/theme.js and templates/product.js

### ISSUE THREAD

**Issue by qedric** [hayes0724/shopify-packer#78]
**Describe the bug**

In my theme.js I have several imports. I have two different product templates; product and product.alternate. Because they share the same JS, I've created a module (scripts/modules/product-template.js) and successfully importing into both /scripts/templates/product.js and /scripts/templates/product.alternate.js.

Within the scripts/modules/product-template.js, i'm attempting to import a module that is also imported by /scripts/layout/theme.js

When I add the import to either theme.js or product-template.js, it works, but when I add it to both, the build fails.

Strangely, I have one other shared module that doesn't cause any errors. I've tried making exact copies of it but it doesn't make any difference

I have throughly checked the module and created test modules with the same result.

**To Reproduce**
1. create a valid/tested 'hello-world' module under /scripts/modules/test.js with export default 'MyTest' for example
2. import the module 'import MyTest from "../modules/test.js"; to theme.js and also to product.js
3. run Packer Build

**Expected behavior**
A build with no errors

**Screenshots**
` ERROR in SplitChunksPlugin
Cache group "default" conflicts with existing chunk.
Both have the same name "layout.theme" and existing chunk is not a parent of the selected modules.
Use a different name for the cache group or make sure that the existing chunk is a parent (e. g. via dependsOn).
HINT: You can omit "name" to automatically create a name.
BREAKING CHANGE: webpack < 5 used to allow to use an entrypoint as splitChunk. This is no longer allowed when the entrypoint is not a parent of the selected modules.
Remove this entrypoint and add modules to cache group's 'test' instead. If you need modules to be evaluated on startup, add them to the existing entrypoints (make them arrays). See migration guide of more info.

webpack 5.28.0 compiled with 1 error in 6410 ms
C:\Users\Q\AppData\Roaming\nvm\v15.6.0\node_modules\@hayes0724\shopify-packer\cli\commands\build.js:42
    if (stats.compilation.errors.length) throw Error('Compile errors');
                                               ^

Error: Compile errors
    at C:\Users\Q\AppData\Roaming\nvm\v15.6.0\node_modules\@hayes0724\shopify-packer\cli\commands\build.js:42:48
    at C:\Users\Q\AppData\Roaming\nvm\v15.6.0\node_modules\@hayes0724\shopify-packer\node_modules\webpack\lib\webpack.js:132:8
    at C:\Users\Q\AppData\Roaming\nvm\v15.6.0\node_modules\@hayes0724\shopify-packer\node_modules\webpack\lib\HookWebpackError.js:69:3
    at Hook.eval [as callAsync] (eval at create (C:\Users\Q\AppData\Roaming\nvm\v15.6.0\node_modules\@hayes0724\shopify-packer\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\Q\AppData\Roaming\nvm\v15.6.0\node_modules\@hayes0724\shopify-packer\node_modules\tapable\lib\Hook.js:18:14)
    at Cache.shutdown (C:\Users\Q\AppData\Roaming\nvm\v15.6.0\node_modules\@hayes0724\shopify-packer\node_modules\webpack\lib\Cache.js:150:23)
    at C:\Users\Q\AppData\Roaming\nvm\v15.6.0\node_modules\@hayes0724\shopify-packer\node_modules\webpack\lib\Compiler.js:1104:15
    at Hook.eval [as callAsync] (eval at create (C:\Users\Q\AppData\Roaming\nvm\v15.6.0\node_modules\@hayes0724\shopify-packer\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\Q\AppData\Roaming\nvm\v15.6.0\node_modules\@hayes0724\shopify-packer\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.close (C:\Users\Q\AppData\Roaming\nvm\v15.6.0\node_modules\@hayes0724\shopify-packer\node_modules\webpack\lib\Compiler.js:1102:23)`

**System (please complete the following information):**
 - OS: Windows 10
 - Node Version v15.6.0.
 - NPM Version 7.4.0
 - Browser NA

**Packer (please complete the following information):**
 - Version 2.1.3 and earlier

**Theme (please complete the following information):**
 - [Shopify Packer theme](https://github.com/hayes0724/packer-blank-theme) - occurs on 2 different custom themes both of which were started from Shopify Packer Theme

**Comment by hayes0724** [comment]
This is part of webpack 5 optimization changes, without editing the config you can't share modules between layout and template entry points.

> BREAKING CHANGE: webpack < 5 used to allow to use an entrypoint as splitChunk. This is no longer allowed when the entrypoint is not a parent of the selected modules.

This is the [Webpack issue](https://github.com/webpack/webpack/issues/6977#issuecomment-470602315) and solution

Packer already has a way of dealing with this, in 2.1.5 it will be the default will be false, in previous builds it's set to true so you need to disable it.

packer.config.js
```
module.exports = {
  'build.sharedBundles': false,
}

```
