### ISSUE TITLE
[BUG] Javascript and CSS in packer versions >1.3.8 don't compile and/or don't evaluate

### ISSUE THREAD

**Issue by adrianocr** [hayes0724/shopify-packer#88]
For me all packer versions above 1.3.8 successfully compile (as in there are no errors in the terminal) and upload but the JS doesn't evaluate and the CSS file(s) are blank. 

If I open the browser inspector I can see a `<script>` and `<link>` tag before `</head>`. If I open the JS file(s) link in a new tab I can see the code is correctly in there, but the browser doesn't load or evaluate the javascript code webpack builds; it never runs. I emptied all the JS code and placed `console.log('testing packer in [template name here]')` in each template and you never see a single console message on any of the templates. Likewise if you open the CSS file(s) through their address in a new tab they are completely blank for me, like packer isn't actually compiling and bundling the CSS. 

This project was NOT built on packer-blank-theme; it was an existing project that I retroactively added packer to. And this worked beautifully up until 1.3.8 but after I upgrade to the latest versions the same exact setup no longer works. 

OS: macOS 11.3
Node: v14.16.0
Yarn: 1.22.10 

Perhaps also related to https://github.com/hayes0724/shopify-packer/issues/76

**Comment by hayes0724** [comment]
@adrianocr I think this is a macOS issue with SSL, in v1.3.8 the method for using and creating SSL was changed. I unfortunately don't have a mac to test on so this is taking a while to debug.

**Comment by hayes0724** [comment]
@adrianocr Fixed pushed in #89 see issue #76 or updated [SSL docs](https://hayes0724.github.io/shopify-packer/docs/ssl/#trusting-the-ca)
