### ISSUE TITLE
"Theme name is required" error while creating new theme

### ISSUE THREAD

**Issue by holymp2006** [hayes0724/shopify-packer#9]
While creating a new project, following the documentation's Quick Start; On step 3. `packer theme:create`, I get the error `Theme name is required`.

my `config.json` file:

````
...
"development": {
      "id": "",
      "password": "xxxxxxxxxxxxxxxxxxxxx",
      "store": "xxxxxxx.myshopify.com",
      "ignore": ["settings_data.json"]
    }
 ...
````

**Comment by hayes0724** [comment]
when using `packer theme:create` it needs to know what name to give the theme on Shopify, example:

`packer theme:create --name="My New Theme"`

This will create a new (empty) theme on Shopify with the same name. Then you can use `deploy` to upload your files or `start` to begin working on them. When the command runs you see the **theme id** for the newly created theme. Add this to your config file above.

**Comment by holymp2006** [comment]
I noticed I was missing the `--name` flag in the command.
I made a pull request #10 to indicate this in the doc's Quick Start.
