### ISSUE TITLE
After running packer build & packer deploy, packer start is not working anymore [BUG]

### ISSUE THREAD

**Issue by OneX** [hayes0724/shopify-packer#93]
**Describe the bug**
After i build and deployed my theme with packer, packer start is not working anymore. I can't see any css update on first deploy or while writing code.

**To Reproduce**
1. packer build
2. packer deploy --env=development
3. packer start
4. Code is not updated and live updates don't work

**Expected behavior**
Localhost server should run with live updates working.

**System (please complete the following information):**
 - OS: [OSX]
 - Node Version [14.16.0]
 - NPM Version [6.14.11]
 - Browser [Brave]

**Packer (please complete the following information):**
 - Version [1.0.9]

**Theme (please complete the following information):**
 - [Shopify Packer theme](https://github.com/hayes0724/packer-blank-theme) [false]

**Comment by hayes0724** [comment]
@OneX Are you sure you are running packer v1.0.9? current version is v2.2.0, can you confirm this is the version of packer used?

> packer build
packer deploy --env=development

This is how you build and deploy for production and is not used for dev. You should only need `packer start`, this will make a dev build and deploy. Production mode (used in build/deploy) will not update or have hmr. In some cases production files are left behind before running start which can cause this issue. Packer deletes the dist folder to prevent this but sometimes it helps to do manually.

Any screenshots of the your terminal or the website (with dev tools console open) will help.

**Comment by OneX** [comment]
Sorry, i saw readme file which had old version. Version is Shopify Packer - v2.1.5.

I don't have any error in my terminal or browser console that is related to packer. Anyway, i guess easiest will be to remove all files and start from scratch.

I tried to delete dist folder localy but it does not work. I guess connecting to browsersync is lost somewhere.

**Comment by OneX** [comment]
Okay, i will give it a try. Thank you for your time.
